### PR TITLE
Add an economy system

### PR DESCRIPTION
**Pull request by PhantomKnight287**
1. Add Economy Commands(Balance,earn,deposit)
2. Add Fun Commands(Food,Dog)

### CODE REVIEW

**Comment by ujjwal-kr** [comment]
testing @0xMrNight 
cc. @0xGamer

**Comment by 0xMrNight** [comment]
https://github.com/PhantomKnight287/discord-assistant-js/blob/88dcf181ce12a398bceada42496475aef1559f83/commands/economy/balance.js#L15-L20

Why have you complicated this so much? The user option can be fetched using the [`getUser`](https://discord.js.org/#/docs/main/stable/class/CommandInteractionOptionResolver?scrollTo=getUser) method.

An example:
image

**Comment by PhantomKnight287** [comment]
Thanks for telling me this. I was completely unaware of this function. This thing will be fixed next time.

**Comment by 0xMrNight** [comment]
Getting this error:
```sql
create table `users` (`userId` varchar(255), `wallet` varchar(255), `bank` varchar(255), `bankLimit` varchar(255), `workingAs` varchar(255), `lastWorked` varchar(255)) - ER_TABLE_EXISTS_ERROR: Table 'users' already exists
```

image

**Comment by 0xMrNight** [comment]
It's working now, dropped the db and recreated

**Review by 0xMrNight — APPROVED** [review]
Nice work, everything is working 👍

**Comment by 0xGamer** [comment]
Please delete Commands/fun/food.js

**Comment by PhantomKnight287** [comment]
1. remove all files in commands/fun and add commands/fun/meme.js
2. fix a bug in create account command
3. change the duration from `3200000`ms to `360000`ms which is complete 60mins

**Comment by PhantomKnight287** [comment]
fix a bug in deposit.js 
image

**Pull request merged**
